### ISSUE TITLE
Provide rules in their original format?

### ISSUE THREAD

**Issue by TheSnoozer** [cyclone-github/rules#2]
Hello,
thanks for this project and all related ones :-)

While it is great to have a format that contains all the rules, sorted by prop, would it also be possible to provide the original rules?

The main idea is that smaller rules could be used to run some quick smoke tests if the data is worth "it".

Thank you for your time and consideration.

**Comment by cyclone-github** [comment]
You can do this manually by downloading the rules and using whichever ones fit your needs.

I included all *.rule files that came with hashcat v6.2.6
https://hashcat.net/hashcat/

Plus OneRuleToRuleThemAll.rule
https://notsosecure.com/one-rule-to-rule-them-all

**Comment by TheSnoozer** [comment]
Yes, I'm aware that some of the rules just come from hashcat and the onetorule them all.

Is there a source for the cyclone_xxx-rules too? Like the cyclone_mini, cyclone_1500, cyclone_5000, cyclone_mst? If so then this is indeed irrelevant :-) Thanks again.

**Comment by cyclone-github** [comment]
No, I have only publicly released cyclone_250. None of my cyclone rulesets are included in "all_rules".
